"""add episode article_published_at

Revision ID: 1eaf48a74266
Revises: 6c806f44935d
Create Date: 2026-09-24 03:59:27.968884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eaf48a74266'
down_revision: Union[str, Sequence[str], None] = '6c806f44935d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('article_published_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episodes', 'article_published_at')
    # ### end Alembic commands ###
