"""add article generation pipeline models

Revision ID: 6c806f44935d
Revises: 9d7cf2188f5a
Create Date: 2026-09-21 19:07:10.154882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c806f44935d'
down_revision: Union[str, Sequence[str], None] = '9d7cf2188f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Manually added, same reasoning/pattern as 9d7cf2188f5a: autogenerate
    # does not detect new values on an existing Postgres native ENUM type.
    # IF NOT EXISTS makes this idempotent for a downgrade -> upgrade cycle
    # (downgrade() below deliberately does not, and cannot, remove it).
    op.execute("ALTER TYPE job_type ADD VALUE IF NOT EXISTS 'ARTICLE_GENERATION'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_plans',
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('introduction_summary', sa.Text(), nullable=False),
    sa.Column('conclusion_summary', sa.Text(), nullable=False),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id')
    )
    op.create_table('articles',
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('article_plan_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_plan_id'], ['article_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id')
    )
    op.create_table('topics',
    sa.Column('transcript_id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('chunk_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('key_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('subtopics', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transcript_id', 'sequence_number', name='uq_topic_order')
    )
    op.create_index(op.f('ix_topics_episode_id'), 'topics', ['episode_id'], unique=False)
    op.create_index(op.f('ix_topics_transcript_id'), 'topics', ['transcript_id'], unique=False)
    op.create_table('article_sections',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('heading', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('supporting_chunk_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('supporting_topic_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'sequence_number', name='uq_article_section_order')
    )
    op.create_index(op.f('ix_article_sections_article_id'), 'article_sections', ['article_id'], unique=False)
    op.create_table('validation_results',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_article_id'), 'validation_results', ['article_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_results_article_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_article_sections_article_id'), table_name='article_sections')
    op.drop_table('article_sections')
    op.drop_index(op.f('ix_topics_transcript_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_episode_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_table('articles')
    op.drop_table('article_plans')
    # ### end Alembic commands ###

    # NOT reverted: the 'ARTICLE_GENERATION' value added to job_type above
    # -- same reasoning as 9d7cf2188f5a's downgrade (Postgres has no
    # ALTER TYPE ... DROP VALUE; harmless to leave for a dev/test rollback).
