"""add chunk model

Revision ID: 9d7cf2188f5a
Revises: 78e3d5ee683d
Create Date: 2026-09-15 18:36:24.192039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d7cf2188f5a'
down_revision: Union[str, Sequence[str], None] = '78e3d5ee683d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Manually added: Alembic autogenerate does not detect new values on an
    # existing Postgres native ENUM type, only table/column changes. Safe
    # inside this transaction on Postgres 12+ as long as the new value
    # isn't used in the same transaction (it isn't). IF NOT EXISTS makes
    # this idempotent -- required because downgrade() (below) can't remove
    # the value again, so a downgrade -> upgrade cycle would otherwise hit
    # "enum label already exists" on the second upgrade (found by actually
    # running that cycle, same class of bug as the initial migration).
    op.execute("ALTER TYPE job_type ADD VALUE IF NOT EXISTS 'TRANSCRIPT_PROCESSING'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks',
    sa.Column('transcript_id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('source_segment_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transcript_id', 'sequence_number', name='uq_chunk_order')
    )
    op.create_index(op.f('ix_chunks_episode_id'), 'chunks', ['episode_id'], unique=False)
    op.create_index(op.f('ix_chunks_transcript_id'), 'chunks', ['transcript_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_transcript_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_episode_id'), table_name='chunks')
    op.drop_table('chunks')
    # ### end Alembic commands ###

    # NOT reverted: the 'TRANSCRIPT_PROCESSING' value added to job_type
    # above. Postgres has no ALTER TYPE ... DROP VALUE; removing one
    # requires rebuilding the enum type (rename, recreate, migrate the
    # column, drop the old type) -- overkill for a downgrade path that
    # exists for dev/test safety, not production rollback. Leaving the
    # unused value in place is harmless.
